### ISSUE TITLE
Unholster times in Guns printout has weird rounding?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/AoAWikiHelperMod#23]
Every unholster time value in the printout are 0.1-0.3 seconds different than what's on the wiki. I don't know if the new printout is more correct or not (I hope they're incorrect so we don't have to change all those pages). This seems to be the case for all guns.

Also the thrown weapons are in the guns printout for some reason.

**Comment by Tslat** [comment]
This one poses an interesting conundrum.

The reason this happens is because clay blocks don't drop clay blocks, they drop balls.
Because of this, my current implementation ignores the drop because it doesn't know that the balls are the intended drop of the block (I have no way of knowing)

To resolve this, I'd have to allow autosmelt tools (emberstone) to smelt _all_ drops from a given block. This poses an issue with compatibility for other mods, and potentially drops for skills and other events too

**Comment by Tslat** [comment]
Bad news

The new value is more correct. Sorry.
This is due to the way rounding is/was done, with the old system trimming off at 2 digits of precision before rounding, whereas the new system is more precise in rounding
